#!/bin/bash

#run after trimmomatic_array.sh and change the files to match those corresponding to your assemblies
megahit=/datacommons/yoderlab/programs/MEGAHIT-1.2.9-Linux-x86_64-static/bin/megahit
unmapped_ids=($(cat /cwork/hpk4/megahit/metadata/names_all_excl_Tsim.txt)) #file with IDs only
META_FILE=/cwork/hpk4/megahit/metadata/good_paths_all.txt #file generated by reads.awk script with full paths

for id in ${unmapped_ids[@]}; do
	read_1p_path=$(grep "$id" "$META_FILE" | cut -f 3 | head -n 1)
        read_2p_path=$(grep "$id" "$META_FILE" | cut -f 4 | head -n 1)
	read_1up_path=$(grep "$id" "$META_FILE" | cut -f 5 | head -n 1)
	read_2up_path=$(grep "$id" "$META_FILE" | cut -f 6 | head -n 1)

        "${megahit}" -1 "${read_1p_path}" -2 "${read_2p_path}" -r "${read_1up_path}","${read_2up_path}" -o /cwork/hpk4/megahit/assemblies/$id.assembly
done
