#!/usr/bin/env bash

#Run after reads.awk once you have a file containing the id, will need to edit awk depending on where the reads are
unmapped_ids=($(cat /cwork/hpk4/megahit/metadata/names_all_excl_Tsim.txt)) #file with IDs only
META_FILE=/cwork/hpk4/megahit/metadata/good_paths_all.txt #file generated by reads.awk script will full paths

for id in ${unmapped_ids[@]}; do
	read_1_path=$(grep "$id" "$META_FILE" | cut -f 1 | head -n 1)
        read_2_path=$(grep "$id" "$META_FILE" | cut -f 2 | head -n 1)

	echo "read 1: ${read_1_path} // read 2: ${read_2_path}"

	java -jar /datacommons/yoderlab/programs/Trimmomatic-0.36/trimmomatic-0.36.jar PE \
	-phred33 -threads 12 "${read_1_path}" "${read_2_path}" \
	/cwork/hpk4/megahit/trimmed/"${id}"_1_paired.fastq.gz /cwork/hpk4/megahit/trimmed/"${id}"_1_unpaired.fastq.gz \
	/cwork/hpk4/megahit/trimmed/"${id}"_2_paired.fastq.gz /cwork/hpk4/megahit/trimmed/"${id}"_2_unpaired.fastq.gz \
	LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

done
